USE [ElectricalApps]
GO

/****** Object:  Table [dbo].[DRV_GRP_V1000]    Script Date: 9/7/2018 2:56:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DRV_GRP_V1000](
	[IDX] [int] IDENTITY(1,1) NOT NULL,
	[DRV_GRP] [nvarchar](50) NOT NULL,
	[DRV_GRP_DESC] [nvarchar](100) NOT NULL,
	[DRV_LIST_IDX] [int] NOT NULL,
 CONSTRAINT [PK_DRV_GRP_V1000] PRIMARY KEY CLUSTERED 
(
	[DRV_GRP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

