USE [ElectricalApps]
GO

/****** Object:  Table [dbo].[DRV_LIST]    Script Date: 9/7/2018 2:56:28 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DRV_LIST](
	[IDX] [int] NULL,
	[DRV_NUM] [nvarchar](50) NOT NULL,
	[DRV_DESC] [nvarchar](100) NULL,
	[DRV_MFR] [nvarchar](100) NULL,
	[DRV_MFR_NUM] [nvarchar](100) NULL,
	[DRV_PARAM_LIST] [nvarchar](50) NULL,
	[DRV_GRP_DESC] [nvarchar](50) NULL,
 CONSTRAINT [PK_DRV_LIST] PRIMARY KEY CLUSTERED 
(
	[DRV_NUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

