USE [ElectricalApps]
GO

/****** Object:  Table [dbo].[MACH_DATA]    Script Date: 9/7/2018 2:56:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MACH_DATA](
	[IDX] [int] IDENTITY(1,1) NOT NULL,
	[MACH_CODE] [nvarchar](10) NOT NULL,
	[MACH_DESC] [nvarchar](50) NULL,
	[DRV_CNT] [int] NOT NULL,
	[DRV1_NAME] [nvarchar](50) NULL,
	[DRV2_NAME] [nvarchar](50) NULL,
	[DRV3_NAME] [nvarchar](50) NULL,
	[DRV4_NAME] [nvarchar](50) NULL,
	[DRV5_NAME] [nvarchar](50) NULL,
	[CHRT_CNT] [int] NULL,
 CONSTRAINT [PK_MACH_DATA] PRIMARY KEY CLUSTERED 
(
	[MACH_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MACH_DATA] ADD  CONSTRAINT [DF_MACH_DATA_CHRT_CNT]  DEFAULT ((0)) FOR [CHRT_CNT]
GO

