USE [ElectricalApps]
GO

/****** Object:  Table [dbo].[TMPLT_DRV]    Script Date: 9/7/2018 2:57:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TMPLT_DRV](
	[IDX] [int] IDENTITY(1,1) NOT NULL,
	[REG_ADDR] [int] NOT NULL,
	[PARAM_NUM] [nvarchar](10) NOT NULL,
	[PARAM_NAME] [nvarchar](100) NOT NULL,
	[MULTIPLIER] [int] NULL,
	[NUM_BASE] [int] NULL,
	[UNITS] [nvarchar](10) NULL,
 CONSTRAINT [PK_TMPLT_DRV] PRIMARY KEY CLUSTERED 
(
	[PARAM_NUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TMPLT_DRV] ADD  CONSTRAINT [DF_TMPLT_DRV_MULTIPLIER]  DEFAULT ((1)) FOR [MULTIPLIER]
GO

ALTER TABLE [dbo].[TMPLT_DRV] ADD  CONSTRAINT [DF_TMPLT_DRV_NUM_BASE]  DEFAULT ((10)) FOR [NUM_BASE]
GO

