USE [ElectricalApps]
GO

/****** Object:  Table [dbo].[TMPLT_CHART]    Script Date: 9/7/2018 2:57:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TMPLT_CHART](
	[IDX] [int] NULL,
	[PARAM_NUM] [nvarchar](10) NOT NULL,
	[PARAM_NAME] [nvarchar](50) NULL,
	[PARAM_VAL] [int] NULL,
 CONSTRAINT [PK_CHRT_TBL] PRIMARY KEY CLUSTERED 
(
	[PARAM_NUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

